#! /bin/bash
set -eux

docker build -t minted/openresty-bundle-deb .
CONTAINER=$(docker create minted/openresty-bundle-deb)
if [ ! -d ./artifacts ]; then
    mkdir ./artifacts
fi
docker cp $CONTAINER:/build/openresty_1.11.2.2-minted_amd64.deb ./artifacts/
docker rm $CONTAINER
